[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 功能 pbrm

## 单账号
> topicLinkUID=`1872BE46778A`


### 下载收藏 update

#### 下载所有收藏
- TOPIC
<pre>1872BDED6B3A</pre>

##### 下载图片
- TOPIC
<pre>1872BD1C0B9A</pre>

##### 下载动图

###### ffmpeg合成gif

####### 储存meta信息和作品本体
> topicLinkUID=`1872BD1C0B9A`


######## 跳过下载作品\(仍会下载meta\) \-\-skip\-download

######## 跳过下载meta数据\(已失效的仍然会下载meta,虽然唯一有价值的数据是id了\) \-\-skip\-meta

##### 下载小说\(暂无\)
- TOPIC
<pre>1872BD1C0B9A</pre>

##### 下载漫画\(暂无\)
- TOPIC
<pre>1872BD1C0B9A</pre>

#### 更新收藏
> topicLinkUID=`1872BDED6B3A`


##### 更新新添加的收藏

##### 更新同时删除已取消收藏的作品\(已失效的也会被删除\) \-\-auto\-remove

##### 强制更新所有收藏\(已保存的收藏将会重新下载，会跳过已失效的收藏\) \-\-force\-update

###### 强制更新作品本体\(对于已存在的作品,该选项比skip\-download优先级更高,skip\-meta同理\) \-\-force\-update\-illust

###### 强制更新所有meta数据 \-\-force\-update\-meta

### 删除收藏 delete

#### 删除指定作品 \<PID\>

#### 删除指定tag所有作品\(暂无\) tag \<tag\>

### 配置

#### 修改配置 config

##### cookie配置 cookie

###### 显示cookie

###### 更新cookie \<cookie\>

##### 配置动图保存模式 ugoira

###### 显示模式

###### 保存为gif\(需ffmpeg\) gif

###### 保存为多张图片 raw

##### 手动配置ffmpeg路径\(环境变量里包含ffmpeg就不需要了\)\(暂无\) ffmpeg

###### 显示配置的ffmpeg路径

###### 设置路径 \<FPATH\>

#### 修改仓库路径\(会自动把仓库搬到新路径\) set

##### 显示仓库路径

##### 设置当前路径为仓库 this

##### 设置指定路径为仓库 \<PATH\>

### 统计信息 show

#### 失效且未保存的收藏 unavailable
- TOPIC
<pre>1872BDF733BA</pre>

#### 失效但已保存的收藏 unavailableSaved

##### 只显示数量 \-\-only\-number
> topicLinkUID=`1872BDF733BA`


#### 已保存的收藏 saved
- TOPIC
<pre>1872BDF733BA</pre>

#### 未保存的收藏\(即需要更新\)\(暂无\) needUpdate
- TOPIC
<pre>1872BDF733BA</pre>

## 多账号\(暂无\)
> topicLinkUID=`1872BE44DAEA`

- TOPIC
<pre>1872BE46778A</pre>

### 多账号配置

## 云端仓库\(暂无\)
- TOPIC
<pre>1872BE44DAEA</pre>

### 本地下载再上传

### 云端直接下载

### 云端管理
